# Generated by Django 5.0.1 on 2024-02-02 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_desc', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('importance', models.IntegerField()),
                ('is_complete', models.BooleanField()),
                ('completion_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.user')),
            ],
            options={
                'unique_together': {('task_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.user')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Work_Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('technique', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.user')),
            ],
            options={
                'unique_together': {('session_id', 'user', 'task')},
            },
        ),
    ]
