# Generated by Django 4.2.9 on 2024-04-07 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='taskDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_Assign_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
