# Generated by Django 4.2.9 on 2024-04-15 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist", name="deadline", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="importance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='taskDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="task_Assign_Date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="manage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
