# Generated by Django 4.2.9 on 2024-04-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_tasklist_deadline_tasklist_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='manage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
