# Generated by Django 4.2.7 on 2024-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasklist_deadline_tasklist_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='category',
            field=models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('College', 'College'), ('Mindfulness', 'Mindfulness')], default='Fitness', max_length=20),
        ),
    ]
