# Generated by Django 4.2.9 on 2024-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_tasklist_manage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
